<?php
/**
 * 
 * Implements hook_form_alter();
 * @param unknown_type $form
 * @param unknown_type $form_state
 * @param unknown_type $form_id
 */
function bundle_inherit_node_form_alter(&$form, &$form_state, $form_id){
  $entity = entity_get_info('node');
  if($form_id == 'node_type_form' && empty($form['#node_type']->type) && count($entity['bundles']) > 0){
    bundle_inherit_attache_inherit_form($form, $form_state, 'node');
    $form['bundle_inherit']['#group'] = 'additional_settings';
    $form['#submit'][] = 'bundle_inherit_node_form_submit';
  }
}

/**
 * 
 * Additional submit handler to the 'node_type_form' form. Perform inherit operations.
 * @param unknown_type $form
 * @param unknown_type $form_state
 */
function bundle_inherit_node_form_submit(&$form, &$form_state){
  /**
   * Check if body field instance already exists.
   */
  if(isset($form_state['values']['bundle_inherit']['inherit']) && $form_state['values']['bundle_inherit']['inherit']){
    if($instance = field_info_instance('node', 'body', trim($form_state['values']['type']))){
      field_delete_instance($instance);
    }
    bundle_inherit_attache_inherit_form_submit(trim($form_state['values']['type']), $form, $form_state);
  }
}